version: "3.9"

# networks:
#   internal:
#     driver: bridge

services:

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=qwerty
    ports:
      - 27016:27017
  app:
    build: .
    restart: always
    ports:
      - "7777:7777"
    environment:
      - DB_HOST=mongodb
    depends_on:
      - mongodb
